### ISSUE TITLE
How to implement it??

### ISSUE THREAD

**Issue by digicomsujan** [agungsugiarto/codeigniter4-orm#4]

**Comment by agungsugiarto** [comment]
Hello @digicomsujan It's currently in beta, not recommended for use in production, but if you're interested in using it locally, you can install with composer.json set to **"minimum-stability": "dev"** and run it with the command composer:

```sh
composer require agungsugiarto/codeigniter4-orm
```

#### Example usage
you can see in unit testing https://github.com/agungsugiarto/codeigniter4-orm/blob/a7e1b616d358286869af8284dcc4a94e8e4d463f/tests/DatabaseEloquentBelongsToManyChunkByIdTest.php#L1-L121


```php
$userWithArticles = BelongsToManyChunkByIdTestTestUser::with('articles')->get();
```


#### More info usefull link docs laravel
- [Database: Getting Started](https://laravel.com/docs/8.x/database)

- [Eloquent: Getting Started](https://laravel.com/docs/8.x/eloquent)

**Comment by digicomsujan** [comment]
Thanks for the reply. I will try using it.
